# Generated by Django 4.0.4 on 2022-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsletterrecipients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
