# Generated by Django 4.0.4 on 2022-05-31 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_alter_newsletterrecipients_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterrecipients',
            options={'verbose_name_plural': 'News Letter Recipients'},
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
