# Generated by Django 4.0.4 on 2022-06-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_article_article_image_alter_article_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
    ]
